[2024-04-19T14:15:37.074+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_data_pipeline.run_power_data_manipulation manual__2024-04-19T14:15:28.553506+00:00 [queued]>
[2024-04-19T14:15:37.085+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_data_pipeline.run_power_data_manipulation manual__2024-04-19T14:15:28.553506+00:00 [queued]>
[2024-04-19T14:15:37.086+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-04-19T14:15:37.100+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): run_power_data_manipulation> on 2024-04-19 14:15:28.553506+00:00
[2024-04-19T14:15:37.107+0000] {standard_task_runner.py:60} INFO - Started process 83 to run task
[2024-04-19T14:15:37.111+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'my_data_pipeline', 'run_power_data_manipulation', 'manual__2024-04-19T14:15:28.553506+00:00', '--job-id', '320', '--raw', '--subdir', 'DAGS_FOLDER/my_data_pipeline.py', '--cfg-path', '/tmp/tmp8uo61dm4']
[2024-04-19T14:15:37.113+0000] {standard_task_runner.py:88} INFO - Job 320: Subtask run_power_data_manipulation
[2024-04-19T14:15:37.185+0000] {task_command.py:423} INFO - Running <TaskInstance: my_data_pipeline.run_power_data_manipulation manual__2024-04-19T14:15:28.553506+00:00 [running]> on host 437b151e2c54
[2024-04-19T14:15:37.305+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_data_pipeline' AIRFLOW_CTX_TASK_ID='run_power_data_manipulation' AIRFLOW_CTX_EXECUTION_DATE='2024-04-19T14:15:28.553506+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-19T14:15:28.553506+00:00'
[2024-04-19T14:15:37.308+0000] {logging_mixin.py:188} INFO - No TXT file found in the directory
[2024-04-19T14:15:37.309+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-19T14:15:37.320+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=my_data_pipeline, task_id=run_power_data_manipulation, execution_date=20240419T141528, start_date=20240419T141537, end_date=20240419T141537
[2024-04-19T14:15:37.365+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-19T14:15:37.388+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
