[2024-04-19T13:50:57.769+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_data_pipeline.run_power_data_manipulation manual__2024-04-19T13:40:50.292561+00:00 [queued]>
[2024-04-19T13:50:57.776+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_data_pipeline.run_power_data_manipulation manual__2024-04-19T13:40:50.292561+00:00 [queued]>
[2024-04-19T13:50:57.777+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 3
[2024-04-19T13:50:57.789+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): run_power_data_manipulation> on 2024-04-19 13:40:50.292561+00:00
[2024-04-19T13:50:57.793+0000] {standard_task_runner.py:60} INFO - Started process 103 to run task
[2024-04-19T13:50:57.796+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'my_data_pipeline', 'run_power_data_manipulation', 'manual__2024-04-19T13:40:50.292561+00:00', '--job-id', '314', '--raw', '--subdir', 'DAGS_FOLDER/my_data_pipeline.py', '--cfg-path', '/tmp/tmpykhgoof3']
[2024-04-19T13:50:57.798+0000] {standard_task_runner.py:88} INFO - Job 314: Subtask run_power_data_manipulation
[2024-04-19T13:50:57.842+0000] {task_command.py:423} INFO - Running <TaskInstance: my_data_pipeline.run_power_data_manipulation manual__2024-04-19T13:40:50.292561+00:00 [running]> on host d89b3a90e99f
[2024-04-19T13:50:57.911+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_data_pipeline' AIRFLOW_CTX_TASK_ID='run_power_data_manipulation' AIRFLOW_CTX_EXECUTION_DATE='2024-04-19T13:40:50.292561+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-19T13:40:50.292561+00:00'
[2024-04-19T13:50:57.912+0000] {logging_mixin.py:188} INFO - No TXT file found in the directory
[2024-04-19T13:50:57.913+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-19T13:50:57.921+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=my_data_pipeline, task_id=run_power_data_manipulation, execution_date=20240419T134050, start_date=20240419T135057, end_date=20240419T135057
[2024-04-19T13:50:57.970+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-19T13:50:57.996+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
